package net.bomeneer.java;

import java.util.*;

import static java.lang.System.nanoTime;
import static java.lang.System.out;

public class dobblebackground {
    static int flnow = 0;
    //dobblesteen waardes
    static String t1 = "[---]\n[   ]\n[ * ]\n[---]";
    static String t2 = "[---]\n[ * ]\n[ * ]\n[---]";
    static String t3 = "[---]\n[  *]\n[ **]\n[---]";
    static String t4 = "[---]\n[** ]\n[** ]\n[---]";
    static String t5 = "[---]\n[ **]\n[***]\n[---]";
    static String t6 = "[---]\n[***]\n[***]\n[---]";
    static String t7 = "*********\n*     *\n *  7  *\n*      *\n*********";
    static String t8 = "*********\n*     *\n *  8  *\n*      *\n*********";
    static String t9 = "*********\n*     *\n *  9  *\n*      *\n*********";
    static String t10 = "*********\n*     *\n *  10 *\n*      *\n*********";
    static String t11 = "*********\n*     *\n *  11 *\n*      *\n*********";
    static String t12 = "*********\n*     *\n *  12 *\n*      *\n*********";
    static String t13 = "*********\n*     *\n *  13 *\n*      *\n*********";
    static String t14 = "*********\n*     *\n *  14 *\n*      *\n*********";
    static String t15 = "*********\n*     *\n *  15 *\n*      *\n*********";
    static String t16 = "*********\n*     *\n *  16 *\n*      *\n*********";
    static String t17 = "*********\n*     *\n *  17 *\n*      *\n*********";
    static String t18 = "*********\n*     *\n *  18 *\n*      *\n*********";
    static String t19 = "*********\n*     *\n *  19 *\n*      *\n*********";
    static String t20 = "*********\n*     *\n *  20 *\n*      *\n*********";
    static String t21 = "*********\n*     *\n *  21 *\n*      *\n*********";
    static String t22 = "*********\n*     *\n *  22 *\n*      *\n*********";
    static String t23 = "*********\n*     *\n *  23 *\n*      *\n*********";
    static String t24 = "*********\n*     *\n *  24 *\n*      *\n*********";
    static String t25 = "*********\n*     *\n *  25 *\n*      *\n*********";
    static String t26 = "*********\n*     *\n *  26 *\n*      *\n*********";
    static String t27 = "*********\n*     *\n *  27 *\n*      *\n*********";
    static String t28 = "*********\n*     *\n *  28 *\n*      *\n*********";
    static String t29 = "*********\n*     *\n *  29 *\n*      *\n*********";
    static String t30 = "*********\n*     *\n *  30 *\n*      *\n*********";
    static String t31 = "*********\n*     *\n *  31 *\n*      *\n*********";
    static String t32 = "*********\n*     *\n *  32 *\n*      *\n*********";
    static String t33 = "*********\n*     *\n *  33 *\n*      *\n*********";
    static String t34 = "*********\n*     *\n *  34 *\n*      *\n*********";
    static String t35 = "*********\n*     *\n *  35 *\n*      *\n*********";
    static String t36 = "*********\n*     *\n *  36 *\n*      *\n*********";
    static String t37 = "*********\n*     *\n *  37 *\n*      *\n*********";
    static String t38 = "*********\n*     *\n *  38 *\n*      *\n*********";
    static String t39 = "*********\n*     *\n *  39 *\n*      *\n*********";
    static String t40 = "*********\n*     *\n *  40 *\n*      *\n*********";
    static String t41 = "*********\n*     *\n *  41 *\n*      *\n*********";
    static String t42 = "*********\n*     *\n *  42 *\n*      *\n*********";
    static String t43 = "*********\n*     *\n *  43 *\n*      *\n*********";
    static String t44 = "*********\n*     *\n *  44 *\n*      *\n*********";
    static String t45 = "*********\n*     *\n *  45 *\n*      *\n*********";
    static String t46 = "*********\n*     *\n *  46 *\n*      *\n*********";
    static String t47 = "*********\n*     *\n *  47 *\n*      *\n*********";
    static String t48 = "*********\n*     *\n *  48 *\n*      *\n*********";
    static String t49 = "*********\n*     *\n *  49 *\n*      *\n*********";
    static String t50 = "*********\n*     *\n *  50 *\n*      *\n*********";
    static String t51 = "*********\n*     *\n *  51 *\n*      *\n*********";
    static String t52 = "*********\n*     *\n *  52 *\n*      *\n*********";
    static String t53 = "*********\n*     *\n *  53 *\n*      *\n*********";
    static String t54 = "*********\n*     *\n *  54 *\n*      *\n*********";
    static String t55 = "*********\n*     *\n *  55 *\n*      *\n*********";
    static String t56 = "*********\n*     *\n *  56 *\n*      *\n*********";
    static String t57 = "*********\n*     *\n *  57 *\n*      *\n*********";
    static String t58 = "*********\n*     *\n *  58 *\n*      *\n*********";
    static String t59 = "*********\n*     *\n *  59 *\n*      *\n*********";
    static String t60 = "*********\n*     *\n *  60 *\n*      *\n*********";
    static String t61 = "*********\n*     *\n *  61 *\n*      *\n*********";
    static String t62 = "*********\n*     *\n *  62 *\n*      *\n*********";
    static String t63 = "*********\n*     *\n *  63 *\n*      *\n*********";
    static String t64 = "*********\n*     *\n *  64 *\n*      *\n*********";
    static String t65 = "*********\n*     *\n *  65 *\n*      *\n*********";
    static String t66 = "*********\n*     *\n *  66 *\n*      *\n*********";
    static String t67 = "*********\n*     *\n *  67 *\n*      *\n*********";
    static String t68 = "*********\n*     *\n *  68 *\n*      *\n*********";
    static String t69 = "*********\n*     *\n *  69 *\n*      *\n*********";
    static String t70 = "*********\n*     *\n *  70 *\n*      *\n*********";
    static String t71 = "*********\n*     *\n *  71 *\n*      *\n*********";
    static String t72 = "*********\n*     *\n *  72 *\n*      *\n*********";
    static String t73 = "*********\n*     *\n *  73 *\n*      *\n*********";
    static String t74 = "*********\n*     *\n *  74 *\n*      *\n*********";
    static String t75 = "*********\n*     *\n *  75 *\n*      *\n*********";
    static String t76 = "*********\n*     *\n *  76 *\n*      *\n*********";
    static String t77 = "*********\n*     *\n *  77 *\n*      *\n*********";
    static String t78 = "*********\n*     *\n *  78 *\n*      *\n*********";
    static String t79 = "*********\n*     *\n *  79 *\n*      *\n*********";
    static String t80 = "*********\n*     *\n *  80 *\n*      *\n*********";
    static String t81 = "*********\n*     *\n *  81 *\n*      *\n*********";
    static String t82 = "*********\n*     *\n *  82 *\n*      *\n*********";
    static String t83 = "*********\n*     *\n *  83 *\n*      *\n*********";
    static String t84 = "*********\n*     *\n *  84 *\n*      *\n*********";
    static String t85 = "*********\n*     *\n *  85 *\n*      *\n*********";
    static String t86 = "*********\n*     *\n *  86 *\n*      *\n*********";
    static String t87 = "*********\n*     *\n *  87 *\n*      *\n*********";
    static String t88 = "*********\n*     *\n *  88 *\n*      *\n*********";
    static String t89 = "*********\n*     *\n *  89 *\n*      *\n*********";
    static String t90 = "*********\n*     *\n *  90 *\n*      *\n*********";
    static String t91 = "*********\n*     *\n *  91 *\n*      *\n*********";
    static String t92 = "*********\n*     *\n *  92 *\n*      *\n*********";
    static String t93 = "*********\n*     *\n *  93 *\n*      *\n*********";
    static String t94 = "*********\n*     *\n *  94 *\n*      *\n*********";
    static String t95 = "*********\n*     *\n *  95 *\n*      *\n*********";
    static String t96 = "*********\n*     *\n *  96 *\n*      *\n*********";
    static String t97 = "*********\n*     *\n *  97 *\n*      *\n*********";
    static String t98 = "*********\n*     *\n *  98 *\n*      *\n*********";
    static String t99 = "*********\n*     *\n *  99 *\n*      *\n*********";
    static String t100 = "*********\n*     *\n *  100 *\n*      *\n*********";
    static String space = "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
    static Random random = new Random();
    static int uitkomst;
    public static void dobblie(int typethrow){
        if(typethrow == 0){uitkomst = random.nextInt(6);}
        else if(typethrow == 1){uitkomst = random.nextInt(100);}
        else {
            out.println("Oops, an unfixable error has occured");
            System.exit(1);
        }
        uitkomst++;
        forlooper();
        if(typethrow == 1){forlooper2();}
        forlooper();
        out.println(space);
        switch (uitkomst) {
            case 1 -> out.println(t1);
            case 2 -> out.println(t2);
            case 3 -> out.println(t3);
            case 4 -> out.println(t4);
            case 5 -> out.println(t5);
            case 6 -> out.println(t6);
            case 7 -> out.println(t7);
            case 8 -> out.println(t8);
            case 9 -> out.println(t9);
            case 10 -> out.println(t10);
            case 11 -> out.println(t11);
            case 12 -> out.println(t12);
            case 13 -> out.println(t13);
            case 14 -> out.println(t14);
            case 15 -> out.println(t15);
            case 16 -> out.println(t16);
            case 17 -> out.println(t17);
            case 18 -> out.println(t18);
            case 19 -> out.println(t19);
            case 20 -> out.println(t20);
            case 21 -> out.println(t21);
            case 22 -> out.println(t22);
            case 23 -> out.println(t23);
            case 24 -> out.println(t24);
            case 25 -> out.println(t25);
            case 26 -> out.println(t26);
            case 27 -> out.println(t27);
            case 28 -> out.println(t28);
            case 29 -> out.println(t29);
            case 30 -> out.println(t30);
            case 31 -> out.println(t31);
            case 32 -> out.println(t32);
            case 33 -> out.println(t33);
            case 34 -> out.println(t34);
            case 35 -> out.println(t35);
            case 36 -> out.println(t36);
            case 37 -> out.println(t37);
            case 38 -> out.println(t38);
            case 39 -> out.println(t39);
            case 40 -> out.println(t40);
            case 41 -> out.println(t41);
            case 42 -> out.println(t42);
            case 43 -> out.println(t43);
            case 44 -> out.println(t44);
            case 45 -> out.println(t45);
            case 46 -> out.println(t46);
            case 47 -> out.println(t47);
            case 48 -> out.println(t48);
            case 49 -> out.println(t49);
            case 50 -> out.println(t50);
            case 51 -> out.println(t51);
            case 52 -> out.println(t52);
            case 53 -> out.println(t53);
            case 54 -> out.println(t54);
            case 55 -> out.println(t55);
            case 56 -> out.println(t56);
            case 57 -> out.println(t57);
            case 58 -> out.println(t58);
            case 59 -> out.println(t59);
            case 60 -> out.println(t60);
            case 61 -> out.println(t61);
            case 62 -> out.println(t62);
            case 63 -> out.println(t63);
            case 64 -> out.println(t64);
            case 65 -> out.println(t65);
            case 66 -> out.println(t66);
            case 67 -> out.println(t67);
            case 68 -> out.println(t68);
            case 69 -> out.println(t69);
            case 70 -> out.println(t70);
            case 71 -> out.println(t71);
            case 72 -> out.println(t72);
            case 73 -> out.println(t73);
            case 74 -> out.println(t74);
            case 75 -> out.println(t75);
            case 76 -> out.println(t76);
            case 77 -> out.println(t77);
            case 78 -> out.println(t78);
            case 79 -> out.println(t79);
            case 80 -> out.println(t80);
            case 81 -> out.println(t81);
            case 82 -> out.println(t82);
            case 83 -> out.println(t83);
            case 84 -> out.println(t84);
            case 85 -> out.println(t85);
            case 86 -> out.println(t86);
            case 87 -> out.println(t87);
            case 88 -> out.println(t88);
            case 89 -> out.println(t89);
            case 90 -> out.println(t90);
            case 91 -> out.println(t91);
            case 92 -> out.println(t92);
            case 93 -> out.println(t93);
            case 94 -> out.println(t94);
            case 95 -> out.println(t95);
            case 96 -> out.println(t96);
            case 97 -> out.println(t97);
            case 98 -> out.println(t98);
            case 99 -> out.println(t99);
            case 100 -> out.println(t100);
        }
        out.println("You've thrown"+ " " + uitkomst);
    }


    public static void forlooper(){
        while(flnow <=6){
            out.println(space);
            switch (flnow) {
                case 1 -> out.println(t1);
                case 2 -> out.println(t2);
                case 3 -> out.println(t3);
                case 4 -> out.println(t4);
                case 5 -> out.println(t5);
                case 6 -> out.println(t6);
            }
            try {Thread.sleep(200);} catch (InterruptedException e) {e.printStackTrace(); }
            flnow++;
        }
        flnow = 0;
    }

    public static void forlooper2() {
        flnow = 7;
        while(flnow <=100){
            out.println(space);
            switch (flnow) {
                case 7 -> out.println(t7);
                case 8 -> out.println(t8);
                case 9 -> out.println(t9);
                case 10 -> out.println(t10);
                case 11 -> out.println(t11);
                case 12 -> out.println(t12);
                case 13 -> out.println(t13);
                case 14 -> out.println(t14);
                case 15 -> out.println(t15);
                case 16 -> out.println(t16);
                case 17 -> out.println(t17);
                case 18 -> out.println(t18);
                case 19 -> out.println(t19);
                case 20 -> out.println(t20);
                case 21 -> out.println(t21);
                case 22 -> out.println(t22);
                case 23 -> out.println(t23);
                case 24 -> out.println(t24);
                case 25 -> out.println(t25);
                case 26 -> out.println(t26);
                case 27 -> out.println(t27);
                case 28 -> out.println(t28);
                case 29 -> out.println(t29);
                case 30 -> out.println(t30);
                case 31 -> out.println(t31);
                case 32 -> out.println(t32);
                case 33 -> out.println(t33);
                case 34 -> out.println(t34);
                case 35 -> out.println(t35);
                case 36 -> out.println(t36);
                case 37 -> out.println(t37);
                case 38 -> out.println(t38);
                case 39 -> out.println(t39);
                case 40 -> out.println(t40);
                case 41 -> out.println(t41);
                case 42 -> out.println(t42);
                case 43 -> out.println(t43);
                case 44 -> out.println(t44);
                case 45 -> out.println(t45);
                case 46 -> out.println(t46);
                case 47 -> out.println(t47);
                case 48 -> out.println(t48);
                case 49 -> out.println(t49);
                case 50 -> out.println(t50);
                case 51 -> out.println(t51);
                case 52 -> out.println(t52);
                case 53 -> out.println(t53);
                case 54 -> out.println(t54);
                case 55 -> out.println(t55);
                case 56 -> out.println(t56);
                case 57 -> out.println(t57);
                case 58 -> out.println(t58);
                case 59 -> out.println(t59);
                case 60 -> out.println(t60);
                case 61 -> out.println(t61);
                case 62 -> out.println(t62);
                case 63 -> out.println(t63);
                case 64 -> out.println(t64);
                case 65 -> out.println(t65);
                case 66 -> out.println(t66);
                case 67 -> out.println(t67);
                case 68 -> out.println(t68);
                case 69 -> out.println(t69);
                case 70 -> out.println(t70);
                case 71 -> out.println(t71);
                case 72 -> out.println(t72);
                case 73 -> out.println(t73);
                case 74 -> out.println(t74);
                case 75 -> out.println(t75);
                case 76 -> out.println(t76);
                case 77 -> out.println(t77);
                case 78 -> out.println(t78);
                case 79 -> out.println(t79);
                case 80 -> out.println(t80);
                case 81 -> out.println(t81);
                case 82 -> out.println(t82);
                case 83 -> out.println(t83);
                case 84 -> out.println(t84);
                case 85 -> out.println(t85);
                case 86 -> out.println(t86);
                case 87 -> out.println(t87);
                case 88 -> out.println(t88);
                case 89 -> out.println(t89);
                case 90 -> out.println(t90);
                case 91 -> out.println(t91);
                case 92 -> out.println(t92);
                case 93 -> out.println(t93);
                case 94 -> out.println(t94);
                case 95 -> out.println(t95);
                case 96 -> out.println(t96);
                case 97 -> out.println(t97);
                case 98 -> out.println(t98);
                case 99 -> out.println(t99);
                case 100 -> out.println(t100);
            }
            try {Thread.sleep(200);}
            catch (InterruptedException e) {e.printStackTrace(); }
            flnow++;
        }
        flnow = 0;
    }
}