# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle build test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'zulu', 'temurin' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 17 (${{ matrix.distribution }})
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
